auth_config.php
languages/en-GB/website_code/php/management/site.inc
setup/basic.sql
setup/index.php
setup/page3.php
setup/page4.php
upgrade.php
website_code/php/management/site.php
website_code/php/management/site_details_management.php
website_code/scripts/management.js

This modification:
1.	Removes manual setting of $xerte_toolkits_site->authentication_method from auth_config.php
2.	adds a new option for setting ‘Authentication Method’ during the setup process (at the end of setup/page3.php). 
3.	adds a new option for setting ‘Authentication Method’ to the admin/management area. 
4.	adds upgrade function for existing installs
In response to http://lists.nottingham.ac.uk/pipermail/xerte-dev/2015-November/008118.html.
See screenshots and fuller logic attached.
[Xerte-Move-Authentication-to-Database.pdf](https://github.com/thexerteproject/xerteonlinetoolkits/files/34737/Xerte-Move-Authentication-to-Database.pdf)

Move authentication to setup

---

modules/xerte/scorm1.2/xttracking_scorm1.2.js
modules/xerte/scorm2004.3rd/xttracking_scorm2004.3rd.js

1) Removed a wrong increment of "pages_visited" when SCORM Tracking Mode is in "tracking of first pass". The pages_visited counter was incremented each time the page is accessed.
2) Fix a problem in SCORM 1.2. When a course with score is finished with status passed, moving fast between pages cause the status change to failed.

Fix in xttracking_scorm scripts.

---

modules/xerte/scorm1.2/xttracking_scorm1.2.js
modules/xerte/scorm2004.3rd/xttracking_scorm2004.3rd.js

Fix for issues #433 and #434.
#433
The suspend_data is not saved when course becomes "completed" so the last visited page is not recorded as visited.
#434
With a SCORM First Pass Tracking Mode course the first score is not preserved if we revisit any page that report a score.

Fix for issues #433 and #434.

---

website_code/php/properties/access_change_template.php

The function db_query(), when UPDATE query, return the number of rows affected,  if you don't change the access setting but still click 'change access', the function db_query() return 0, since no row has been changed. If execute query fail, return false.

Fix bug #371

---

modules/decision/delete_template.php
modules/site/delete_template.php
modules/xerte/delete_template.php

When deleting a project subdirectores and files can be left behind. In the function 'delete_folder_loop' the initial directory path is not set correctly - the directory separator is missing. This causes the subsequent 'is_dir' to fail, and so everything ends up being treated as a file. In the function 'clean_up_files' trying to delete the 'file' then fails because it is a directory.

Correct pathname used during deletes.

---

website_code/php/error_library.php
website_code/php/management/site.php
website_code/php/management/site_details_management.php
website_code/scripts/management.js

When logged in as the admin, and selecting the 'Error handling settings', it is not possible to change the error log maximum (entry) size. The display box is present, but in the background it is tied to the 'error_email_message' entry (which governs whether an error log entry should be mailed to users). In addition the database 'max_error_size' entry is not updated (another mix up in the code).
It seems that the database entry 'error_email_message' (and textarea id from the admin UI) are never used. The entry is not actually required though since whether an error log entry should be emailed to users or not can easily be controlled by the 'email_error_list' value (which is a list of userids that should receive the email message). If the list is empty, then obviously no email should be …

Error config - fix for error handling settings

---

plugins.php

The 'glob' function may return an error, and this will cause the following 'array_merge' and foreach calls to throw a warning:
"PHP Warning:  array_merge(): Argument #1 is not an array..."
"PHP Warning:  Invalid argument supplied for foreach() in..."

Plugins.php - ensure array variables are set before merging.

---

setup/page_password.php
setup/php_modules.php
setup/php_modules_iframe.php
setup/php_modules_test.php

During the setup of Xerte 3.5, found some sentences either truncated or slightly wrong grammatically.
In particular for the upload_tmp_dir check I received:
> Look in the Ini file for upload_tmp_dir = and set the value to a path outside of the public area 
> available to visitors to the web server (e.g if you are using XAMPP - you should not put the temp 
> directory in the HTDOCS folder): try changing this setting to
> Not set!
and for the database connection check
> Sorry, the attempt to connect to MySql on the host 127.0.0.1 has failed using account xxx.
> MySQL reports the following error -
(nothing is then shown - the problem was actually caused by SELinux)
Both of these have now been tidied up to make more sense if things are not set or no error message from MySQL is available.

Corrections to some of the messages displayed during setup

---

languages/en-GB/management.inc
languages/en-GB/website_code/php/management/error_list.inc
management.php
website_code/php/management/delete_error_list.php
website_code/php/management/error_list.php
website_code/php/management/site_details_management.php

The current management/admin UI handles all the log files as 'Errors'. The fact that successful events are logged as well, indicates that errors is not really accurate.
This is a series of (initially 4) commits which modifies the UI so that 'Errors' is now shown as 'Log files'. The log files themselves can now be selected by the standard management Show/Hide buttons. (Previously only the grey 'View' button was shown, and remained as 'View' even when the log file was displayed/selected.) The button label to delete all the ('error') log files has been changed, and when it is confirmed to delete the log files the confirmation message says that all the log files have been deleted (not just error logs).
I have made no change to the 'error_log_path' variable, since it is used throughout Xerte …

Log file changes

---

library/Xerte/Authentication/Ldap.php
logout.php
management.php
website_code/php/error_library.php
website_code/php/login_library.php
website_code/php/logout.php
website_code/php/management/play_security_management.php
website_code/php/management/template_details_management.php
website_code/php/management/user_details_management.php
website_code/php/user_library.php

I think this is the last of the commits we have for log files. Basically we have tried to do 2 things: 1) Log config changes to a MGMT log file (for security we would want to know when changes were made and ideally by whom); (2) log user login attempts and logouts to a separate LOGINS log file. We can then tie up when a user was logged in if required. Failed logins are shown in red. This should make it easier to spot repeated login attempts. For the admin user the username is not recorded. For all users the IP address is recorded.
All other user activity goes to the log file for the specific user.

Log logins logouts etc

---

setup/page3.php
setup/page_password.php
website_code/php/management/site.php
website_code/scripts/management.js

This is basically the same as the LDAP password fix. The passwd could contain HTML characters (e.g. '&'), and these should not be interpreted when displaying the password.
The password can be set during Xerte installation. This has been catered for but not tested.

Admin pwd fix

---

website_code/php/management/site.php

Noticed that when I changed the authentication method in the administrator UI dropdown list, it showed the current entry twice. (In my case, the list became - 'Ldap, Guest, Ldap,..' changing it to Guest, I then got 'Guest, Guest, Ldap...) This is a bit confusing.
I have modified the code so that the currently selected option is still highlighted (selected), but entries are only shown once.
Although this code looks a bit CPU intensive, the authentication method is probably rarely changed once it has been set.

Sort out authentication dropdown list so options only shown once.

---

website_code/php/user_library.php

Some msgs when a new user logs in do not specify the username or their login/database id number. These commits, now include the username in msgs, and the id number for failure messages. It may be useful info when trying to sort out a users problem. Adding the username when a msg gets logged to the users own log file is a bit redundant, but the msgs get logged at the SUCCESS/CRITICAL level too, and the username is need in there.

Tidy up login log msgs

---

website_code/php/import/fileupload.php

The 'stripos' function is supported in PHP 5 and 7. The Xerte FAQ says that the minimum spec for PHP should be 5 (http://www.xerte.org.uk/index.php?option=com_faqbook&view=category&id=138&Itemid=567&lang=en]). So it should be safe to use this function.
However, if it is felt that it may cause problems, then perhaps the check should become:
`if(!strpos($php_check,"<?PHP") && !strpos($php_check,"<?php")){`

PHP file uploads should check for PHP case-independently.

---

library/Xerte/Validate/FileExtension.php

This commit stems from a message I sent to the forum: []http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=928&Itemid=759&lang=en#3048
A user uploading a project from a Linux PC to a Linux Xerte server, may well have files with no extension on them.

Non-windows files do not require a file extension.

---

editor/upload.php
website_code/php/scorm/export.php

This is for part 1 of the issue #689. The admin user does not have the logon username variable set, so we have to explicitly check for the sysadmin.
Ironically the hard part (for me) was what to do with the 'die' statement. I couldn't figure out how to change it so the popup gave an actual error message rather than just 'error'. I'm assuming 'error' is the browser javascript default message. I tried wrapping it in html/javascript but that made no difference. I don't understand the context that the code is being run in, so that is probably why usual tricks are not working. Using exit rather than die stopped the popup from appearing, and I think that would be confusing for the user. (They click on 'Publish', it fails but there is no error message of any kind.)
I have included an _debug …

Allow the admin user to publish and export projects. Fix for #689

---

upgrade.php

The commit has two changes:
1) If the BLOB or TEXT mysql field type is given, then no DEFAULT value is added to the DB query.
2) If the 'after' field to the '_db_add_field' function is not specified, then no 'AFTER' option is included in the DB query. (Basically, if it's not specified (or rather is null), then add the field to the end of the table. This saves trying to work out the name of the last field.)

Adding mysql fields - minor changes to '_db_add_field'

---

setup/page2.php

Recently modifying 'setup/basic.sql' caused a newline to be added to the file. When 'explode' is used to create an array of DB queries, the last query becomes just the newline - which db_query doesn't like.
Previously a check was made that the line is not empty (""). This commit changes that to check that the line length is more than 1 character.
An alternative fix would be to use (on line 84):
`if ( $query !=""  && $query != "\n")`

Fix for issue #699

---

upgrade.php

In response to issue #696 this commit will display any new MIME types added to the allowed list during an upgrade. Admins can then decide for themselves if they want to modify the list further.

Issue #696 - display any new MIME types added to allow list during upgrade.

---

languages/en-GB/website_code/scripts/workspaceproperties_tab.js
website_code/scripts/import.js
website_code/scripts/workspaceproperties_tab.js

The ClamAV check in particular can take some time  (unless clamdscan is used). These commits add a spinner to show that something is happening. It changes the 'Upload' button icon into 'Uploading...' and adds a small spinner next to it.
The upload icon can be found by logging in; highlight 'Workspace'; click on 'Properties' icon above; then click on 'Import' tab.

Add a spinner when uploading a project zip file.

---

editor/importpages/merge.php

Noticed the following errors:
======
PHP Warning:  array_push() expects parameter 1 to be array, string given in /var/www/html/xerte-3.5/editor/importpages/merge.php on line 90
======
It looks like the arguments to the array_push call were the wrong way round. This commits swaps them around.

Editor import merge fix.

---

library/Xerte/Validate/FileExtension.php
library/Xerte/Validate/FileMimeType.php
plugins/file_uploading-extension-check.php
plugins/file_uploading-mimetype.php

If a user selected no files for uploading then a file not found error was given. These commits ensure that a 'no file selected' error is shown instead.

Ensure the file checks return the correct error if no file was selected.

---

website_code/scripts/template_management.js

When deleting multiple projects, the projects are deleted but then a final error is popped up saying 'Sorry you cannot delete a folder that has projects in it. Please empty the folder first'.
It seems that the internal list produced includes the 'Workspace' folder, and this cannot be deleted.
The commit just checks for the workspace folder, and skips over it.
Deleting a single project shows no such problem.
Selecting the 'Recycle Bin' folder and clicking on the 'Delete' icon above will prompt if the recycle bin is to be emptied. This works fine, and shows no popup error.
To test the error, log in, then:
highlight multiple projects (using the shift key) from the Workspace folder, then click on the 'Delete' icon near the top;
click through the prompts confirming that the projects are to be …

Remove error when deleting multiple projects.

---

feedback/index.php

Under chrome the top bar on the feedback page shows nothing. Under firefox though it shows a broken image link at the top-left and top-right corners.

Fix broken image links on the feedback page.

---

modules/xerte/parent_templates/Nottingham/models_html5/gapFill.html

Trim whitespace from both ends of the *Fill in Blank* answer string. This will handle an answer as correct if the end user accidentally starts with typing a space for example. 
Also made assignment of `currvalue` identical throughout this script. This made `currvalue` local to the `setTimeout` function. Or should the `currvalue` declared on line 34 be used everywhere?
See [Mozilla trim() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim)

Trim space from both ends of Fill in Blank answer

---

modules/xerte/parent_templates/Nottingham/models_html5/gapFill.html

Adding `autocapitalize="none"` to the `<input>` element of the *Fill in Blank* answer, will disable auto capitalization on iOS. Although Xerte is not case sensitive by default (will treat capitalized answer as correct as well), this gives a much better end user experience.
See [Apple Safari HTML Reference](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize)

No autocapitalize for Fill in Blank input for iOS

---

modules/xerte/parent_templates/Nottingham/models_html5/gapFill.html

Add `autocomplete="off" autocorrect="off" spellcheck="false"` attributes to the `<input>` element of the *Fill in Blank* answer. This will disable auto-completion and auto-correction for (iOS) Safari and other browsers.
See [Apple Safari HTML Reference](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize)
See [Mozilla spellcheck attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck)

No auto-complete and correct for Fill in Blank

---

modules/xerte/parent_templates/Nottingham/models_html5/gapFill.html

This is a **bugfix** to prevent the `#submitBtn` in `setUpDragDrop` to get the same tab-index as the previous item. This is the same as the `tabIndex++;` on line 491 for `setUpFillBlank` for example.

Bugfix: tabIndexx++ for submitBtn in setUpDragDrop

---

modules/xerte/scorm2004.3rd/xttracking_scorm2004.3rd.js

When trying to get the completion status of a Scorm2004 3rd edition
package in Moodle and in 360Learning I noticed that the packages
never completed.
When debugging the JavaScript code I noticed an inconsistency between
the function call 'state.pageCompleted(page_nr)' and the function
definition 'function pageCompleted(sit)'.
The problem seems to have arisen on July 21 2017. When aligning
the names of the variables, the argument of state.pageCompleted()
was changed from 'sit' to 'page_nr'. I think this might be the reason
that my Scorm modules in Moodle and 360Learning had a 'not completed'
status.

Change wrong argumenttype pageCompleted(page_nr)

---

functions.php
modules/xerte/edithtml.php
website_code/php/management/management_library.php
website_code/php/management/new_grouping.php
website_code/php/management/remove_grouping.php

When I switched on $development = true to turn on error logging on Xerte 3.8.5 / PHP 7.4 I got some initial errors in the browser that were clearly not related to the problem I was debugging.
Fixed those first.

Fixed problem of Grouping not showing Xerte 3.8.5 / PHP 7.4

---

edit.php
edithtml.php
languages/en-GB/website_code/php/display_library.inc
website_code/php/versioncontrol/template_close.php

This pull request relates to issues #909 and #842 
The date/time is now added to the lockfile for each user, and the username is correctly extracted when sending out the email notifications.
As mention in #842 only one notification is sent out per user. Also from that issue, the email message wording has been changed. The user did not 'request' notification, they have no way to do that. So it now simply says that the user is being notified.

Lockfile corrections

---

oai-pmh/oai.php

OAI-PMH: make sure deleted record is show when project access is set to anything else than Public

OAI-PMH: make sure deleted record is show when project access is set to Private
